# Generated by Django 4.2.23 on 2025-08-06 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MoneyMaker', '0002_review_parent_alter_review_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='banner',
            field=models.ImageField(blank=True, default='money.jpg', upload_to=''),
        ),
    ]
